# Site settings
title: BuckeyeLAN
email: BuckeyeLAN@osu.edu
description: > # this means to ignore newlines until "baseurl:"
  © 2015 BuckeyeLAN | All Rights Reserved
baseurl: "" # the subpath of your site, e.g. /blog/
url: "cwdg.github.io/buckeye-lan-website/" # the base hostname & protocol for your site
twitter_username: BuckeyeLAN
facebook_link:  facebook.com/BuckeyeLAN

logo_path: "./images/logos/BuckeyeLAN.jpg"

# Build settings
markdown: kramdown
